### ISSUE TITLE
Make vanity url optional

### ISSUE THREAD

**Issue by bprussell** [egineering-llc/urlshortener#5]
Perhaps I don't want to specify a vanity url, I just want to submit a link and get something back that's shorter. I would assume that I would not want links that were generated in this way to show up on the homepage - See #1

**Comment by rorpage** [comment]
Yeah, I think that sounds great!

There is an API endpoint that allows you to POST data to create a new entry, so maybe if you don't specify the `vanity` you get a randomly generated sequence of letters like `3d8bzA7`?

**Comment by bprussell** [comment]
Yes, that's what I had in mind.
