### ISSUE TITLE
Prevent URLs from being overwritten

### ISSUE THREAD

**Issue by bprussell** [egineering-llc/urlshortener#6]
At the moment, if you submit a request for a vanity URL that already exists, the record will get overwritten with the new value. This could cause problems. For example, if I create a link called `/dashboard`, and I don't realize that it already was taken by someone else, I will take over their URL and the link they might have shared with someone else will not work as they intended.

I think that links should be permanent, and if you screw up on your original request, you should just have to think of a new vanity URL to use. However, I could see maybe putting a short window for correcting typos.

**Comment by rorpage** [comment]
At first I thought this was a good idea, so I made it that way on purpose.

I see what you mean though. There are some URLs we don't want overridden ever.
